name: Run Rubocop

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ruby:3.1

    steps:
    - uses: actions/checkout@v2

    - name: Install ruby dependencies
      run: bundler install

    - name: Run rubocop
      run: bundler exec rubocop
